CREATE USER "ccr" WITH ENCRYPTED PASSWORD 'ccr';
ALTER ROLE "ccr" WITH createdb;
CREATE database "ccr";
ALTER DATABASE ccr OWNER TO ccr;



-- Usuario DBA
CREATE ROLE dba WITH LOGIN PASSWORD 'password_dba';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA zoomin TO dba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA zoomin TO dba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA zoomin TO dba;
ALTER DEFAULT PRIVILEGES IN SCHEMA zoomin GRANT ALL ON TABLES TO dba;
ALTER DEFAULT PRIVILEGES IN SCHEMA zoomin GRANT ALL ON SEQUENCES TO dba;
ALTER DEFAULT PRIVILEGES IN SCHEMA zoomin GRANT ALL ON FUNCTIONS TO dba;


-- Usuuario READ ONLY
CREATE ROLE readonly WITH LOGIN PASSWORD 'password_readonly';
GRANT CONNECT ON DATABASE ccr TO readonly;
GRANT USAGE ON SCHEMA zoomin TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA zoomin TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA zoomin GRANT SELECT ON TABLES TO readonly;
