CREATE USER "ccr" WITH ENCRYPTED PASSWORD 'ccr';
ALTER ROLE "ccr" WITH createdb;
CREATE database "ccr";
ALTER DATABASE ccr OWNER TO ccr;



-- ROL DBA
CREATE ROLE dba;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA zoomin TO dba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA zoomin TO dba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA zoomin TO dba;

ALTER DEFAULT PRIVILEGES IN SCHEMA zoomin GRANT ALL ON TABLES TO dba;
ALTER DEFAULT PRIVILEGES IN SCHEMA zoomin GRANT ALL ON SEQUENCES TO dba;
ALTER DEFAULT PRIVILEGES IN SCHEMA zoomin GRANT ALL ON FUNCTIONS TO dba;

-- Usuario con rol dba
CREATE USER dba_user WITH LOGIN PASSWORD 'password_dba';
GRANT dba TO dba_user;


-- Usuuario READ ONLY
CREATE ROLE readonly;

GRANT SELECT ON ALL TABLES IN SCHEMA zoomin TO readonly;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA zoomin TO readonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA zoomin GRANT SELECT ON TABLES TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA zoomin GRANT USAGE, SELECT ON SEQUENCES TO readonly;

-- Usuario con rol readonly
CREATE USER readonly_user WITH LOGIN PASSWORD 'password_readonly';
GRANT readonly TO readonly_user;



